-- ===================================================
-- Module 9: Events, Event Details & Registrations
-- ===================================================

-- 1. Ensure events table exists and has all required columns
CREATE TABLE IF NOT EXISTS events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    organizer VARCHAR(100),
    location VARCHAR(150) NOT NULL,
    event_date VARCHAR(50) NOT NULL,
    event_time VARCHAR(50) NOT NULL,
    image_url VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    community_id BIGINT NULL,
    event_type VARCHAR(50) DEFAULT 'Workshop',
    attendees_count INT DEFAULT 24,
    cover_image VARCHAR(255) DEFAULT '/images/comm_event_detail_cover.png',
    organizer_role VARCHAR(150) DEFAULT 'Organizer',
    organizer_avatar VARCHAR(255) DEFAULT '/images/comm_creative_souls_avatar.png',
    venue VARCHAR(255) DEFAULT 'Art Studio, Mumbai',
    art_form VARCHAR(50) DEFAULT 'All',
    what_youll_learn TEXT,
    who_can_join TEXT,
    things_to_bring TEXT,
    guidelines TEXT,
    quote TEXT,
    is_featured BOOLEAN DEFAULT FALSE
);

-- 2. Create event_registrations table
CREATE TABLE IF NOT EXISTS event_registrations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_event_user (event_id, user_id),
    CONSTRAINT fk_reg_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_reg_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. Seed Realistic Events across Music, Dance, Photography, Painting, and Writing
INSERT INTO events (
    id, title, organizer, organizer_role, organizer_avatar, location, venue, event_date, event_time,
    image_url, cover_image, description, community_id, event_type, attendees_count, art_form,
    what_youll_learn, who_can_join, things_to_bring, guidelines, quote, is_featured
) VALUES
(
    801,
    'Watercolor Basics Workshop',
    'Creative Souls',
    'A community for all kinds of artists.',
    '/images/comm_creative_souls_avatar.png',
    'Mumbai, Maharashtra',
    'Art Studio, 123 Creative Street, Bandra West, Mumbai, Maharashtra 400050',
    '15 Mar 2024',
    '4:00 PM - 6:00 PM (IST)',
    '/images/comm_event_watercolor.png',
    '/images/event_detail_banner_watercolor.png',
    'Learn the fundamentals of watercolor painting with easy techniques and step-by-step guidance. Perfect for beginners and art enthusiasts! This hands-on workshop will introduce you to the world of watercolors. You will learn basic tools, color mixing, different brush techniques, and create your own small artwork by the end of the session. No prior experience is needed - just bring your creativity!',
    601,
    'Workshop',
    32,
    'Painting',
    'Introduction to watercolor materials\nColor mixing and blending techniques\nBrush control and texture creation\nStep-by-step guided painting\nTips and tricks from an experienced artist',
    'Open to all art lovers, especially beginners! No prior experience is required.',
    'A positive attitude!\nMaterials will be provided, but you can also bring your own favorites',
    'Be respectful and supportive\nFollow the venue rules\nNo plagiarism or misuse of content\nKeep the space clean\nHave fun and be creative!',
    'Art is better when shared.',
    TRUE
),
(
    802,
    'Local Artists Exhibition',
    'ArtHouse Collective',
    'Curated contemporary gallery and artist showcase.',
    '/images/artist_ishita_thumb.png',
    'Mumbai, Maharashtra',
    'Community Art Gallery, Heritage Block, Kala Ghoda, Mumbai 400001',
    '22 Mar 2024',
    '10:00 AM - 5:00 PM (IST)',
    '/images/comm_event_exhibition.png',
    '/images/comm_event_detail_cover.png',
    'Explore stunning works from emerging and master artists in our vibrant regional community. Meet the creators, understand their visual storytelling process, and immerse yourself in a diverse spectrum of canvas and sculptured pieces.',
    601,
    'Exhibition',
    48,
    'Painting',
    'Curatorial walkthrough with exhibiting painters\nInsights into composition, scale, and color palettes\nNetworking with collectors, art patrons, and gallery curators',
    'Artists, collectors, art enthusiasts, and anyone who appreciates contemporary Indian visual arts.',
    'Notebook or digital sketchbook for reflections\nComfortable walking shoes',
    'Do not touch framed artworks\nPhotography without flash is permitted\nBe mindful of quiet gallery zones',
    'Every canvas has a heartbeat.',
    FALSE
),
(
    803,
    'Outdoor Sketching Meetup',
    'Creative Souls',
    'Artist community group for outdoor plein air sessions.',
    '/images/comm_creative_souls_avatar.png',
    'Pune, Maharashtra',
    'Riverside Promenade & Heritage Banyan Garden, Pune 411001',
    '28 Mar 2024',
    '3:00 PM - 6:00 PM (IST)',
    '/images/comm_event_sketching.png',
    '/images/comm_event_detail_cover.png',
    'Join fellow artists for a relaxed sketching and observational drawing session at the park. We will capture architectural details, foliage, and twilight lighting in a collaborative, friendly environment.',
    601,
    'Meetup',
    17,
    'Painting',
    'Plein air landscape and urban perspective tips\nQuick gesture sketching in 5-minute intervals\nPeer feedback exchange over tea at sunset',
    'Open to all artists from beginners to seasoned sketchers.',
    'Sketchbook or drawing pad\nPencils, pens, or portable watercolor kits\nA small folding stool or picnic mat',
    'Respect nature and public spaces\nLeave no trace behind\nEncourage other participants',
    'The world reveals itself to those who sketch it.',
    FALSE
),
(
    804,
    'Digital Art Basics (Live Session)',
    'Aanya Deshmukh',
    'Visual artist & digital illustrator.',
    '/images/artist_profile_avatar.png',
    'Online (Google Meet)',
    'Online via Google Meet (Link provided upon registration)',
    '5 Apr 2024',
    '5:00 PM - 7:00 PM (IST)',
    '/images/comm_event_digital_art.png',
    '/images/comm_event_detail_cover.png',
    'Get started with digital art tools, layers, blending modes, and digital brush styling. Perfect for traditional artists transitioning into digital illustration or complete newcomers looking to master software workflows.',
    601,
    'Live Session',
    32,
    'Digital Art',
    'Setting up your canvas, DPI, and resolution\nMastering layer masks, opacity, and clipping masks\nCreating custom brushes and textured strokes\nLive Q&A and artwork critique',
    'Open to anyone with a tablet, iPad, or computer with graphics software.',
    'Graphics tablet or iPad with Procreate / Photoshop / Krita\nStable internet connection for live screenshare',
    'Mute microphone when speaker is presenting\nUse the chat box for questions\nRespect intellectual property of shared tutorial assets',
    'Creativity takes courage and a digital brush.',
    FALSE
),
(
    805,
    'Indie Acoustic Jam & Songwriting Night',
    'Rohan Mehta',
    'Acoustic fingerstyle composer & indie artist.',
    '/images/artist_rohan_avatar.png',
    'Pune, Maharashtra',
    'The Sound Room, 4th Floor, FC Road, Shivaji Nagar, Pune 411005',
    '12 Apr 2024',
    '6:30 PM - 9:30 PM (IST)',
    '/images/opp_campus_band.png',
    '/images/comm_event_detail_cover.png',
    'An intimate evening of original indie songwriting, acoustic guitar picking, and collaborative rhythm sessions. Play your own original tunes, test out newly written lyrics, or simply vibe with our indie collective.',
    NULL,
    'Live Session',
    45,
    'Music',
    'Techniques in alternate guitar tunings (DADGAD, Open D)\nLyric writing structures and finding authentic melody hooks\nLive acoustic improv and collaborative harmonies',
    'Singers, songwriters, acoustic instrumentalists, and music enthusiasts.',
    'Acoustic guitar, ukulele, or small percussion (if playing)\nNotebook for songwriting ideas',
    'Acoustic instruments only (no loud distortion amps)\nSupport each performer warmly\nNo uncredited recording or publishing of fellow artists songs',
    'Where words fail, music speaks.',
    TRUE
),
(
    806,
    'Contemporary Fusion Masterclass',
    'Kavya Iyer',
    'Choreographer & contemporary fusion dancer.',
    '/images/artist_kavya_avatar.png',
    'Bengaluru, Karnataka',
    'Rhythm Movement Studio, 100 Feet Road, Indiranagar, Bengaluru 560038',
    '18 Apr 2024',
    '11:00 AM - 2:00 PM (IST)',
    '/images/opp_dance_performance.png',
    '/images/comm_event_detail_cover.png',
    'Explore the expressive synergy between Indian classical mudras and fluid contemporary floorwork. This masterclass emphasizes emotional expression, body awareness, and ground transitions in modern choreography.',
    NULL,
    'Workshop',
    28,
    'Dance',
    'Contemporary spine release and grounding drills\nBlending Bharatanatyam mudras with contemporary gestures\nChoreography routine to original ambient sitar fusion track',
    'Dancers with basic movement experience or passion for contemporary expression.',
    'Comfortable stretchable dancewear\nWater bottle and small towel\nBarefoot or contemporary dance socks',
    'Warm up before rigorous transitions\nEncourage peer movement\nRespect personal physical limits',
    'Dance is the hidden language of the soul.',
    FALSE
),
(
    807,
    'Golden Hour Street Photography Walk',
    'Arjun Rao',
    'Street & documentary photographer.',
    '/images/artist_arjun_thumb.png',
    'Mumbai, Maharashtra',
    'Marine Drive Promenade & Colaba Causeway, Mumbai 400020',
    '25 Apr 2024',
    '5:00 PM - 7:30 PM (IST)',
    '/images/opp_lens_and_life.png',
    '/images/comm_event_detail_cover.png',
    'Capture the golden rays of sunset reflecting off the Arabian Sea and the bustling evening energy of old Mumbai streets. Learn street portraiture ethics, candid composition, and mastering natural rim lighting.',
    NULL,
    'Meetup',
    36,
    'Photography',
    'Framing and leading lines in chaotic street environments\nManaging dynamic range during golden hour\nEthical approaches to candid street portraiture',
    'Photographers of all levels: DSLR, mirrorless, film, or smartphone shooters welcome.',
    'Any camera or smartphone with manual focus controls\nLens recommendation: 35mm or 50mm prime\nComfortable walking footwear',
    'Be polite and respectful to street vendors and locals\nAsk consent before close-up portraits\nStay together as a photo group',
    'Photography is the story I fail to put into words.',
    FALSE
),
(
    808,
    'Poetry & Storytelling Circle',
    'Words & Worlds Guild',
    'Independent literary circle and authors guild.',
    '/images/comm_words_worlds.png',
    'Mumbai, Maharashtra',
    'Kitab Khana Cafe, Somaiya Bhavan, Fort, Mumbai 400001',
    '2 May 2024',
    '4:00 PM - 6:30 PM (IST)',
    '/images/opp_content_writer.png',
    '/images/comm_event_detail_cover.png',
    'A cozy gathering for writers, poets, and narrative thinkers. Read your poetry, share flash fiction, receive constructive feedback, and explore spontaneous creative writing prompts surrounded by classic literature.',
    NULL,
    'Workshop',
    22,
    'Writing',
    'Sensory imagery and concise meter in modern poetry\nOvercoming writer block through timed word-association games\nBuilding emotional resonance in flash fiction under 500 words',
    'Aspiring and seasoned writers, poets, spoken word performers, and story lovers.',
    'Your favorite notebook, pen, or typed manuscript\n2-3 minutes of material if you wish to read aloud',
    'Constructive and kind feedback only\nRespect diverse literary themes and personal narratives\nNo recording without the author explicit consent',
    'Fill your paper with the breathings of your heart.',
    FALSE
)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    organizer = VALUES(organizer),
    organizer_role = VALUES(organizer_role),
    organizer_avatar = VALUES(organizer_avatar),
    location = VALUES(location),
    venue = VALUES(venue),
    event_date = VALUES(event_date),
    event_time = VALUES(event_time),
    image_url = VALUES(image_url),
    cover_image = VALUES(cover_image),
    description = VALUES(description),
    community_id = VALUES(community_id),
    event_type = VALUES(event_type),
    attendees_count = VALUES(attendees_count),
    art_form = VALUES(art_form),
    what_youll_learn = VALUES(what_youll_learn),
    who_can_join = VALUES(who_can_join),
    things_to_bring = VALUES(things_to_bring),
    guidelines = VALUES(guidelines),
    quote = VALUES(quote),
    is_featured = VALUES(is_featured);

-- 4. Initial Seed Registrations
INSERT IGNORE INTO event_registrations (event_id, user_id) VALUES
(801, 102),
(801, 103),
(801, 104),
(802, 101),
(802, 105),
(805, 101),
(806, 101),
(807, 101);
