package com.artsphere.repository;

import com.artsphere.model.User;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Test
    @DisplayName("Should save, find, and verify existence of a user")
    void testSaveAndFindUser() {
        String uniqueSuffix = String.valueOf(System.currentTimeMillis());
        User user = new User("artist_" + uniqueSuffix, "artist_" + uniqueSuffix + "@artsphere.com", "pass123", "Test Artist");
        user.setBio("Passionate oil painter and illustrator");
        user.setRole("ROLE_ARTIST");

        User saved = userRepository.save(user);

        assertNotNull(saved.getId(), "User ID should be generated by MySQL");

        Optional<User> foundById = userRepository.findById(saved.getId());
        assertTrue(foundById.isPresent(), "User should be found by ID");
        assertEquals(user.getUsername(), foundById.get().getUsername());
        assertEquals("ROLE_ARTIST", foundById.get().getRole());

        Optional<User> foundByUsername = userRepository.findByUsername(user.getUsername());
        assertTrue(foundByUsername.isPresent(), "User should be found by username");

        Optional<User> foundByEmail = userRepository.findByEmail(user.getEmail());
        assertTrue(foundByEmail.isPresent(), "User should be found by email");

        assertTrue(userRepository.existsByUsername(user.getUsername()));
        assertTrue(userRepository.existsByEmail(user.getEmail()));
    }
}
